### ISSUE TITLE
Package inconsistency between sympde and psydac

### ISSUE THREAD

**Issue by spossann** [pyccel/psydac#280] opened 2023-03-06 20:25 UTC
Psydac's `setup.py` says `'sympy>=1.5'`, while `sympde` requires `sympy<1.7,>=1.2`. A psydac install on my machine fetches `sympy-1.11.1-py3-none-any.whl` at the moment, which yields a consistency error.

**Comment by yguclu** [comment] 2023-03-07 08:33
Duplicate of issue #225? Please read [this comment](https://github.com/pyccel/psydac/issues/225#issuecomment-1421156538).

**Closed** 2023-10-19 15:37 UTC
Labels: duplicate
